name = "animehubs"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "animehubs-db"
database_id = "6193c47d-7779-46b8-a5a0-14adb909ed99"
migrations_dir = "src/lib/db/migrations"

[[r2_buckets]]
binding = "R2"
bucket_name = "animehubs-images"
